name: DevSecOps Scan

on: [push, pull_request]

jobs: 
  security-scan:
    runs-on:  ubuntu-latest  
    steps:  
    - name: Checkout code
      uses: actions/checkout@v4

      #verificação de Segredos com Gitleaks
    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Análise Estática de Código (SAST) com Semgrep
    - name: SAST with Semgrep
      run: |
        python3 -m pip install Semgrep
        semgrep --config=auto --sarif --output semgrep-results.sarif .
      continue-on-error: true
 
      # Análise de Dependências (SCA) com OWASP Dependency-check

    - name: SCA with OWASP Dependency-check
      uses: dependency-check/Dependency-Check@main
      with:
        project: 'Meu-Projeto-DevSecOps'
        path: '.'
        format: 'HTML'
      env:
        JAVA_HOME: /opt/jdk
        